volumes:
    website:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/website
    db_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/database
    portainer:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/portainer

services:
    ft_nginx:
        build: requirements/nginx/
        container_name: ft_nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - website:/var/www/html
        depends_on:
            - ft_wordpress
        links:
            - ft_wordpress
        networks:
            - frontend
        restart: always

    ft_mariadb:
        build: requirements/mariadb
        container_name: ft_mariadb
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - SQL_ROOT_PASS=${SQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_USER=root
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASS=${WORDPRESS_DB_PASS}
        networks:
            - database
        restart: always

    ft_wordpress:
        build: requirements/wordpress
        container_name: ft_wordpress
        ports:
            - '9000:9000'
        volumes:
            - website:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=${DB_HOST}
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASS=${WORDPRESS_DB_PASS}
            - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
            - WORDPRESS_USER=${WORDPRESS_USER}
            - WORDPRESS_PASS=${WORDPRESS_PASS}
            - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
            - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
            - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
            - INCEPTION_URL=${INCEPTION_URL}
            - INCEPTION_TITLE=${INCEPTION_TITLE}
            - DOMAIN_NAME=${DOMAIN_NAME}
        depends_on:
            - ft_mariadb
        links:
            - ft_mariadb
            - ft_redis
        networks:
            - frontend
            - database
        restart: always

    ft_redis:
        build: requirements/bonus/redis
        container_name: ft_redis
        ports:
            - '6379:6379'
        networks:
            - database
        restart: always

    ft_ftp:
        build: requirements/bonus/ftp
        container_name: ft_ftp
        ports:
            - '21:21'
            - '30000-30010:30000-30010'
        volumes:
            - website:/var/www/html/
        networks:
            - database
            - frontend
        depends_on:
            - ft_wordpress
        restart: always
        environment:
            FTP_USER: ${FTP_USER}
            FTP_PASSWORD: ${FTP_PASSWORD}

    ft_portainer:
        image: portainer/portainer-ce:latest
        container_name: ft_portainer
        ports:
            - '8000:8000'
            - '9443:9443'
        volumes:
            - portainer:/data
            - '/var/run/docker.sock:/var/run/docker.sock'
        networks:
            - frontend
        restart: always

networks:
    frontend:
        name: frontend
        driver: bridge
    database:
        name: database
        driver: bridge
